### PR TITLE
WIP: Pass keepalived image to mco bootstrap

### PR DESCRIPTION
**Pull request by cybertron**
I believe we will need to do this once we are deploying our services
with mco instead of dev-scripts.

### CODE REVIEW

**Comment by stbenjam** [comment]
Is this based on the comment here: https://github.com/openshift/machine-config-operator/pull/795#issuecomment-504567632?

**Comment by cybertron** [comment]
No, this is just my attempt to get us using the images from the release instead of pointing at our external repos on quay.io.

**Comment by markmc** [comment]
Principle seems sane - for any images we use, we need to get its pullspec from the release image

**Review by bcrochet — COMMENTED** [review]
We will likely need to add the other images too... Coredns, haproxy, mdns-publisher, baremetal-runtimecfg.

**Comment by russellb** [comment]
This is now tracked here: https://github.com/openshift/installer/issues/2067

**Pull request closed without merging**
