### PR TITLE
Rebasing kni-installer on openshift/installer

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
This rebase pulls in a newer version of RHCOS (410.8.20190325.0) in `hack/build.sh`.  I was running into issues with coredns not starting, but that turned out to be that I needed the same fixes from https://github.com/openshift-metalkube/dev-scripts/commit/401ba612a7645801e3046fe0c7424d7aee6d80f1.

I did that, but the bootstrap node is still not bringing up the k8s API.  There's no errors in bootkube, but all progress seems to stop.

**Comment by markmc** [comment]
Note that you're likely seeing the bootstrap launched with an ootpa image whereas the masters are being given a maipo image by dev-scripts. See #37 and openshift-metalkube/dev-scripts#287

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/516/

**Comment by markmc** [comment]
Ok, the rebase/merge looks good mechanically to me, and our path to fixing everything will be based on this rebase ... so I'm going ahead and merging

**Pull request merged**
