### PR TITLE
Remove wait for Ironic

### PR DESCRIPTION
**Pull request by stbenjam**
Will be replaced with a mechanism using the terraform provider.

### CODE REVIEW

**Review by russellb — APPROVED** [review]

**Review by hardys — APPROVED** [review]

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/827/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/828/

**Comment by hardys** [comment]
CI should now be working so re-triggered job at http://10.8.144.11:8080/job/dev-tools/832/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/832/

**Pull request merged**
