### PR TITLE
Reenable SELinux on bootstrap VM

### LINKED ISSUE #63: Turn SELinux back on in bootstrap VM
The following commit turned off SELinux on the bootstrap VM: https://github.com/openshift-metal3/kni-installer/commit/69236afe4d

We need to debug whatever SELinux issues remain and turn this back on.

### PR DESCRIPTION
**Pull request by stbenjam**
Fixes #63

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/618/

**Comment by markmc** [comment]
+1 if this works now - you think it's ok to merge now, @stbenjam ?

**Comment by stbenjam** [comment]
I didn't try with 4.1. I'd expect it probably works but would like to get rc3 sorted first

**Comment by stbenjam** [comment]
Rebased on 4.1.0 rc.3. If CI succeeds, this should be good to merge.

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/640/

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/641/

**Comment by stbenjam** [comment]
@markmc Tests good against 4.1, I think we can merge it

**Comment by markmc** [comment]
Cool

**Pull request merged**
