### PR TITLE
baremetal: Drop early exit during create.

### LINKED ISSUE #60: Remove early exit from installer
Currently we exit early from the installer, and do a bunch of hacks in 06_create_cluster.sh.

- [x] Remove the NoSchedule taint from masters
    - PR: ~~https://github.com/openshift/machine-config-operator/pull/846~~ Merged
    - Can remove on next rebase

- [x] Remove patch_ep_host_etcd
    - PR: https://github.com/openshift-metal3/dev-scripts/pull/620

- [X] ~~Remove csr signing https://github.com/openshift-metal3/dev-scripts/issues/260~~
  - Alternative merged: moved csr signing before running installer https://github.com/openshift-metal3/dev-scripts/pull/621

- [x] Remove add-machine-ips.sh script https://github.com/openshift-metal3/dev-scripts/blob/master/06_create_cluster.sh#L85-L94

### PR DESCRIPTION
**Pull request by russellb**
This is no longer necessary.  See: https://github.com/openshift-metal3/dev-scripts/pull/652

Closes https://github.com/openshift-metal3/kni-installer/issues/60

### CODE REVIEW

**Comment by russellb** [comment]
See https://github.com/openshift-metal3/dev-scripts/pull/652, which changes dev-scripts to no longer perform any actions after the early exit, showing that this safe to merge

**Comment by russellb** [comment]
@stbenjam FYI - a good one to include before the next installer PR update

**Comment by stbenjam** [comment]
We should be able to run CI on this, even without the dev-scripts changes.  We'll see the cluster come up on the `create cluster` command in the logs.  If this passes, I could build a new image on Monday with that small additional installer change, and https://github.com/openshift-metal3/dev-scripts/pull/652 could remove wait_for_cvo finish as well.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/838/

**Comment by markmc** [comment]
Works fine for me, looks like CI failure is unrelated

**Pull request merged**
