### PR TITLE
Restore hashicorp/hcl

### PR DESCRIPTION
**Pull request by stbenjam**
When I removed hclencoder in https://github.com/openshift-metal3/kni-installer/pull/95, hcl was removed as well.  This is still used by terraform-config-inspect and is part of openshift/installer, it's not something we added. I do not know why dep did that, or why CI passed... we only needed to remove hclencoder.

Build failing with:
```
+ go build -ldflags ' -X github.com/openshift-metalkube/kni-installer/pkg/version.Raw=unreleased-master-1235-g70e0f163830fd1482dfa352e5999ce515651bbf8 -X github.com/openshift-metalkube/kni-installer/pkg/version.Commit=70e0f163830fd1482dfa352e5999ce515651bbf8 -s -w' -tags 'libvirt release' -o bin/kni-install ./cmd/kni-install
pkg/terraform/exec/vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/load_legacy.go:7:2: cannot find package "github.com/hashicorp/hcl" in any of:
	/home/stbenjam/go/src/github.com/openshift-metalkube/kni-installer/pkg/terraform/exec/vendor/github.com/hashicorp/hcl (vendor tree)
	/home/stbenjam/go/src/github.com/openshift-metalkube/kni-installer/vendor/github.com/hashicorp/hcl
	/home/stbenjam/go/src/github.com/openshift-metalkube/vendor/github.com/hashicorp/hcl
	/usr/lib/golang/src/github.com/hashicorp/hcl (from $GOROOT)
	/home/stbenjam/go/src/github.com/hashicorp/hcl (from $GOPATH)
```

### CODE REVIEW

**Comment by stbenjam** [comment]
Ah I see why, hclencoder was never added to Gopkg.toml. When I removed it I must have done `rm hcl*` instead of using dep.  Builds always passed locally for me since I have a copy of hashicorp/hcl in `$GOPATH`.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/761/

**Comment by stbenjam** [comment]
CI is not actually testing this PR. https://github.com/openshift-metal3/dev-scripts/pull/628

**Comment by hardys** [comment]
Ok I landed the dev-scripts change and re-triggered CI to hopefully prove it's fixed by this PR

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/764/

**Pull request merged**
