### PR TITLE
rename metalkube to metal3

### PR DESCRIPTION
**Pull request by dhellmann**

### CODE REVIEW

**Comment by russellb** [comment]
I can't seem to build this PR.  I get this error that comes from `hack/build.sh` when I run `05_build_ocp_installer.sh` from dev-scripts.

```
build from your ${GOPATH} (/home/rbryant/go/src/github.com/openshift-metalkube/kni-installer is not in /home/rbryant/go)
```

I think we may need to land this at the same time as switching dev-scripts over to using the new path.

**Comment by dhellmann** [comment]
I get a different error

```
Solving failure: No versions of sigs.k8s.io/cluster-api-provider-azure met constraints:
	openshiftnocluster: unable to update checked out version: fatal: reference is not a tree: b49363c5b3247da8d7345904a3c95d4a28c66a61
: command failed: [git checkout b49363c5b3247da8d7345904a3c95d4a28c66a61]: exit status 128
	master: Could not introduce sigs.k8s.io/cluster-api-provider-azure (from https://github.com/awesomenix/cluster-api-provider-azure.git)@master, as it is not allowed by constraint openshiftnocluster from project github.com/openshift-metal3/kni-installer.
```

**Comment by dhellmann** [comment]
> I can't seem to build this PR. I get this error that comes from `hack/build.sh` when I run `05_build_ocp_installer.sh` from dev-scripts.
> 
> ```
> build from your ${GOPATH} (/home/rbryant/go/src/github.com/openshift-metalkube/kni-installer is not in /home/rbryant/go)
> ```
> I think we may need to land this at the same time as switching dev-scripts over to using the new path.

I think you're right about those 2 patches depending on each other. We will need this one in order for this code to build in the new location, and the other one for the scripts to check it out to that location.

**Comment by honza** [comment]
> build from your ${GOPATH} (/home/rbryant/go/src/github.com/openshift-metalkube/kni-installer is not in /home/rbryant/go

You need to actually rename the directory for this to work.

**Comment by honza** [comment]
I get this error, however.

```
# github.com/openshift-metal3/kni-installer/pkg/destroy/baremetal
pkg/destroy/baremetal/baremetal.go:24:12: undefined: "github.com/openshift-metal3/kni-installer/vendor/github.com/libvirt/libvirt-go".NewConnect
```

**Comment by honza** [comment]
Actually, works fine with:

```
$ TAGS=libvirt ./hack/build.sh
```

**Comment by stbenjam** [comment]
We might just want to skip renaming to metal3, and return everything back to `openshift/installer`.  See: https://github.com/openshift-metal3/kni-installer/issues/66

**Comment by stbenjam** [comment]
Going to close this, we can revisit it if the fork's existence is going to be prolonged, but otherwise we'll just undo the rename all together as part of opening a PR to openshift/insatller.

**Pull request closed without merging**
