### PR TITLE
Rebasing kni-installer on openshift/installer

### PR DESCRIPTION
**Pull request by stbenjam**
Rebasing at the start of sprint 165.

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/543/

**Comment by stbenjam** [comment]
@derekhiggins  GitHub is happy to merge this but looks like CI can't apply the patch.  Any ideas?

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/550/

**Comment by derekhiggins** [comment]
> Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/550/

> $ sync_go_repo_and_patch github.com/openshift-metalkube/kni-installer https://github.com/openshift-metalkube/kni-installer.git
> ...
> Apr 10 16:04:00 |  Failed to merge in the changes.

looks like sync_go_repo_and_patch can't handle this type of rebase, it may need to be tested manually and merged if everything looks ok.

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/551/

**Comment by stbenjam** [comment]
Good install for me (with the linked dev-scripts PR)

```
INFO Install complete!                            
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/root/dev-scripts/ocp/auth/kubeconfig' 
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.ostest.test.metalkube.org
```

**Review by vrutkovs — APPROVED** [review]
Worked great here

**Pull request merged**
