### PR TITLE
Run terraform fmt on baremetal config

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/798/

**Comment by stbenjam** [comment]
Failure due to openshift-metal3/dev-scripts#639, kicked off again http://10.8.144.11:8080/job/dev-tools/799/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/799/

**Comment by stbenjam** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/641

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/805/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/806/

**Pull request merged**
