### PR TITLE
Use clusterinfo to get CLUSTER_DOMAIN

### PR DESCRIPTION
**Pull request by derekhiggins**
We can't rely on /etc/resolv.conf as the domain of the
host may be shared between hosts.

Taking the same approach used in dev-scripts

### CODE REVIEW

**Comment by markmc** [comment]
@derekhiggins since this isn't baremetal specific, I'd hope our goal would be to get this merged into openshift/installer upstream ASAP. Do you forsee any problems with that? If not, I'm fine with carrying this in openshift-metalkube/kni-installer temporarily

**Comment by derekhiggins** [comment]
> @derekhiggins since this isn't baremetal specific, I'd hope our goal would be to get this merged into openshift/installer upstream ASAP. Do you forsee any problems with that? If not, I'm fine with carrying this in openshift-metalkube/kni-installer temporarily

Can do but, there is a bunch of stuff in this file that isn't upstream, including the line being changed by this patch so it can't go upstream until some other parent patches go upstream first.

**Comment by markmc** [comment]
@derekhiggins ah, I missed that going in - ok, this would just be part of the etcd dns discovery patch that eventually should go upstream. Thanks!

@celebdor fine to merge if you're happy with it

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/515/

**Review by celebdor — APPROVED** [review]

**Review by celebdor — APPROVED** [review]

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/545/

**Comment by celebdor** [comment]
Done in #44

**Pull request closed without merging**
