### PR TITLE
Rebase on openshift/installer 4.2.0-0.ci-2019-06-19-140700

### PR DESCRIPTION
**Pull request by stbenjam**
Needs https://github.com/openshift-metal3/dev-scripts/pull/627

### CODE REVIEW

**Comment by stbenjam** [comment]
Install will fail until we get a new MCO that doesn't set the cloud provider for baremetal:
  https://github.com/openshift/machine-config-operator/pull/864

**Comment by stbenjam** [comment]
Install failing due to https://github.com/metal3-io/cluster-api-provider-baremetal/issues/88

**Comment by stbenjam** [comment]
This is good to go, have a clean install.  Will build a release image and update dev-scripts PR after this is merged.


```
[root@dell-r730-021 dev-scripts]# oc get clusterversion
NAME      VERSION                        AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.2.0-0.ci-2019-06-19-140700   True        False         30m     Cluster version is 4.2.0-0.ci-2019-06-19-140700

[root@dell-r730-021 dev-scripts]# oc get nodes
NAME       STATUS   ROLES    AGE   VERSION
master-0   Ready    master   43m   v1.14.0+04ae0f405
master-1   Ready    master   43m   v1.14.0+04ae0f405
master-2   Ready    master   43m   v1.14.0+04ae0f405
worker-0   Ready    worker   20m   v1.14.0+04ae0f405
```

**Comment by hardys** [comment]
Tested locally with openshift-metal3/dev-scripts#627 and I can confirm this is working fine:

```
$ oc get nodes
NAME       STATUS   ROLES    AGE     VERSION
master-0   Ready    master   32m     v1.14.0+04ae0f405
master-1   Ready    master   32m     v1.14.0+04ae0f405
master-2   Ready    master   32m     v1.14.0+04ae0f405
worker-0   Ready    worker   7m39s   v1.14.0+04ae0f405

$ oc get clusterversion
NAME      VERSION                        AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.2.0-0.ci-2019-06-19-140700   True        False         15m     Cluster version is 4.2.0-0.ci-2019-06-19-140700
```

**Pull request merged**
