### PR TITLE
Merge openshift/installer 4.2.0-0.ci-2019-05-29-154816

### PR DESCRIPTION
**Pull request by stbenjam**
To test:
- Check out this PR to ~/go/src/github.com/openshift-metalkube/kni-installer
- Use https://github.com/openshift-metal3/dev-scripts/pull/577
- Run `KNI_INSTALL_FROM_GIT=true make`

Will update the dev-scripts PR with an actual KNI image once this is merged.

See @russellb's comment below, worker deployments don't currently work.

### CODE REVIEW

**Comment by russellb** [comment]
FYI - I expect worker deployments to fail with 4.2 until we merge https://github.com/openshift-metal3/kni-installer/pull/90, which is the last patch before we can close https://github.com/openshift-metal3/dev-scripts/issues/548

**Comment by stbenjam** [comment]
Got it, thanks! At the moment, I'm still stuck on upgrading to terraform 0.12, working through some issues there, so this PR doesn't really get very far.

**Comment by stbenjam** [comment]
So it gets installed, now, at least up to the cluster running. Will test with workers once that PR is merged. I updated the description here in case anyone wants to try this.

**Comment by stbenjam** [comment]
Reminder to myself tomorrow: remove vendored `rodaine/hclencoder`, as we can use JSON now

**Comment by russellb** [comment]
Tested successfully, so lgtm!

**Review by russellb — APPROVED** [review]

**Pull request merged**
